apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
    name: xrprocks-com-tls
spec:
    secretName: xrprocks-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: xrprocks.com
    dnsNames:
        - xrprocks.com
        - www.xrprocks.com
    acme:
        config:
            - http01:
                ingressClass: nginx
            domains:
                - xrprocks.com
                - www.xrprocks.com