apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: 'ken.mei@outlook.com'
        privateKeySecretRef:
            name: letsencrypt-prod
        solver:
            - http01:
                ingress:
                    class: nginx