apiVersion: v1
kind: PersistentVolume
metadata:
        name: postgres-storage
spec:
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: local-storage
        local:
                path: /var/mnt/postgres-storge
        nodeAffinity:
                required:
                        nodeSelectorTerms:
                                - matchExpressions:
                                        - key: kubernetes.io/hostname
                                          operator: In
                                          values:
                                                  - slave-node3
